"""Model package."""

# Fallback list used by model registry in frozen/packaged builds where
# module enumeration may be incomplete.
BUILTIN_MODEL_MODULES = (
    "basilisk_ultimate",
    "basilisk_v2",
    "basilisk_v3",
    "basilisk_v3_35k",
    "basilisk_v3_pro",
    "basilisk_v3_pro_35k",
    "basilisk_v3_x_hyperspeed",
    "basilisk_x_hyperspeed",
    "cobra",
    "cobra_pro",
    "deathadder_elite",
    "deathadder_v2",
    "deathadder_v2_mini",
    "deathadder_v2_pro",
    "deathadder_v2_x_hyperspeed",
    "deathadder_v3",
    "deathadder_v3_hyperspeed",
    "deathadder_v3_pro",
    "deathadder_v4_pro",
    "naga_v2_hyperspeed",
    "naga_v2_pro",
    "naga_x",
    "orochi_v2",
    "viper",
    "viper_8k",
    "viper_mini",
    "viper_ultimate",
    "viper_v2_pro",
    "viper_v3_hyperspeed",
    "viper_v3_pro",
)
